---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "taiga.fullname" . }}-front
  labels: {{- include "taiga.front.labels" . | nindent 4 }}
spec:
  type: {{ .Values.front.service.type }}
  {{- if (or (eq .Values.front.service.type "LoadBalancer") (eq .Values.front.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.front.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{ if eq .Values.front.service.type "LoadBalancer" }}
  loadBalancerSourceRanges: {{ .Values.front.service.loadBalancerSourceRanges }}
  {{ end }}
  {{- if (and (eq .Values.front.service.type "LoadBalancer") (not (empty .Values.front.service.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.front.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: taiga-front
      port: {{ .Values.front.service.port }}
      targetPort: taiga-front
      {{- if (and (eq .Values.front.service.type "NodePort") (not (empty .Values.front.service.nodePorts.http)))}}
      nodePort: {{ .Values.front.service.nodePorts.http }}
      {{- end }}
  selector: {{- include "taiga.front.matchLabels" . | nindent 4 }}
