{{- if .Values.createInitialUser }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "taiga.fullname" . }}-createinitialuser
spec:
  template:
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
      - name: createinitialuser
        image: {{ template "taiga.back.image" . }}
        command:
          - sh
          - /scripts/createinitialuser.sh
        volumeMounts:
          - name: createinitialuser
            mountPath: /scripts
        env:
          - name: POSTGRES_DB
            value: "{{ .Values.postgresql.auth.database }}"
          - name: POSTGRES_USER
            value: "{{ .Values.postgresql.auth.username }}"
          - name: POSTGRES_PASSWORD
            value: "{{ .Values.postgresql.auth.password }}"
          - name: POSTGRES_HOST
            value: {{ default (printf "%s-postgresql" (include "taiga.fullname" .)) .Values.postgresql.host | quote }}
          - name: TAIGA_SECRET_KEY
            value: "{{ .Values.secretKey }}"
      restartPolicy: Never
      volumes:
        - name: createinitialuser
          configMap:
            name: {{ template "taiga.fullname" . }}-createinitialuser
            defaultMode: 0744
  backoffLimit: 4
{{- end }}
