---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "taiga.fullname" . }}-protected
  labels: {{- include "taiga.protected.labels" . | nindent 4 }}
spec:
  type: {{ .Values.protected.service.type }}
  {{- if (or (eq .Values.protected.service.type "LoadBalancer") (eq .Values.protected.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.protected.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{ if eq .Values.protected.service.type "LoadBalancer" }}
  loadBalancerSourceRanges: {{ .Values.protected.service.loadBalancerSourceRanges }}
  {{ end }}
  {{- if (and (eq .Values.protected.service.type "LoadBalancer") (not (empty .Values.protected.service.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.protected.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: taiga-protected
      port: {{ .Values.protected.service.port }}
      targetPort: taiga-protected
      {{- if (and (eq .Values.protected.service.type "NodePort") (not (empty .Values.protected.service.nodePorts.http)))}}
      nodePort: {{ .Values.protected.service.nodePorts.http }}
      {{- end }}
  selector: {{- include "taiga.protected.matchLabels" . | nindent 4 }}
